// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cofrinho.infrastructure.Persistence;

#nullable disable

namespace cofrinho.infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CofrinhoDbContext))]
    [Migration("20250826002652_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Cofrinho")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cofrinho.core.Entities.Objetivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EstaDeletado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Objetivos", "Cofrinho");
                });

            modelBuilder.Entity("cofrinho.core.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaDeletado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ObjetivoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("Transacoes", "Cofrinho");
                });

            modelBuilder.Entity("cofrinho.core.Entities.Objetivo", b =>
                {
                    b.OwnsOne("cofrinho.core.ValueObjects.Dinheiro", "ValorAlvo", b1 =>
                        {
                            b1.Property<Guid>("ObjetivoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MoedaEnum")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ValorAlvo_Moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ValorAlvo");

                            b1.HasKey("ObjetivoId");

                            b1.ToTable("Objetivos", "Cofrinho");

                            b1.WithOwner()
                                .HasForeignKey("ObjetivoId");
                        });

                    b.OwnsOne("cofrinho.core.ValueObjects.Url", "ImagemUrl", b1 =>
                        {
                            b1.Property<Guid>("ObjetivoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ImagemUrl");

                            b1.HasKey("ObjetivoId");

                            b1.ToTable("Objetivos", "Cofrinho");

                            b1.WithOwner()
                                .HasForeignKey("ObjetivoId");
                        });

                    b.Navigation("ImagemUrl");

                    b.Navigation("ValorAlvo")
                        .IsRequired();
                });

            modelBuilder.Entity("cofrinho.core.Entities.Transacao", b =>
                {
                    b.HasOne("cofrinho.core.Entities.Objetivo", "Objetivo")
                        .WithMany("Transacoes")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("cofrinho.core.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid>("TransacaoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MoedaEnum")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Valor_Moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Valor");

                            b1.HasKey("TransacaoId");

                            b1.ToTable("Transacoes", "Cofrinho");

                            b1.WithOwner()
                                .HasForeignKey("TransacaoId");
                        });

                    b.Navigation("Objetivo");

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("cofrinho.core.Entities.Objetivo", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
